### ISSUE TITLE
Problems to install by pip

### ISSUE THREAD

**Issue by jeffersonhsta** [clara-labs/imaplib3#5]
When I try pip install imaplib3 I get the bellow error:
```
$ pip install imaplib3
Collecting imaplib3
  Downloading imaplib3-0.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/4f/1wlr3nd171q162cwyj1jjymh0000gn/T/pip-build-6tgxygv3/imaplib3/setup.py", line 3, in <module>
        import imaplib3
      File "/private/var/folders/4f/1wlr3nd171q162cwyj1jjymh0000gn/T/pip-build-6tgxygv3/imaplib3/imaplib3/__init__.py", line 4, in <module>
        from .base import Server
      File "/private/var/folders/4f/1wlr3nd171q162cwyj1jjymh0000gn/T/pip-build-6tgxygv3/imaplib3/imaplib3/base.py", line 7, in <module>
        import exc
    ImportError: No module named 'exc'

    Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/4f/1wlr3nd171q162cwyj1jjymh0000gn/T/pip-build-6tgxygv3/imaplib3
```

I believe that just replace the ```import exc``` by ```import .exc``` on file ```imaplib3/base.py``` solves this problem

**Comment by jeffersonhsta** [comment]
I fixed that on my pull request, I just forgot link this issue on commit message
